import { NextRequest, NextResponse } from 'next/server';
import { ScanResponse } from '@/lib/scanner/types';

export async function POST(request: NextRequest) {
  let scan: ScanResponse;
  try {
    scan = await request.json();
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body.' }, { status: 400 });
  }

  const html = renderPdfHtml(scan);
  return new NextResponse(html, {
    headers: { 'Content-Type': 'text/html; charset=utf-8' },
  });
}

function renderPdfHtml(scan: ScanResponse): string {
  const scoreColor = scan.score >= 80 ? '#22c55e' : scan.score >= 50 ? '#eab308' : '#ef4444';

  const checksHtml = scan.checks
    .map((c) => {
      const statusColor =
        c.status === 'pass' ? '#22c55e' : c.status === 'warn' ? '#eab308' : '#ef4444';
      const statusLabel =
        c.status === 'pass' ? 'PASS' : c.status === 'warn' ? 'WARNING' : c.status === 'fail' ? 'FAIL' : 'SKIP';

      return `
        <tr>
          <td>${c.label}</td>
          <td><span style="color:${statusColor};font-weight:bold">${statusLabel}</span></td>
          <td>${c.details}</td>
          <td>${c.suggestion || '—'}</td>
        </tr>`;
    })
    .join('');

  const recommendations = scan.checks
    .filter((c) => c.status === 'fail' || c.status === 'warn')
    .map((c) => `<li><strong>${c.label}:</strong> ${c.suggestion}</li>`)
    .join('');

  return `<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <title>Compliance Report — ${scan.url}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #1a1a1a; padding: 40px; max-width: 900px; margin: 0 auto; }
    .header { text-align: center; margin-bottom: 32px; border-bottom: 2px solid #e5e7eb; padding-bottom: 24px; }
    .header h1 { font-size: 20px; color: #111827; }
    .header p { color: #6b7280; font-size: 13px; margin-top: 4px; }
    .score-box { text-align: center; margin: 24px 0; }
    .score-number { font-size: 64px; font-weight: bold; }
    .score-label { font-size: 14px; color: #6b7280; }
    .summary { display: flex; justify-content: center; gap: 24px; margin: 16px 0 32px; }
    .summary span { font-size: 14px; }
    table { width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 13px; }
    th, td { text-align: left; padding: 8px 12px; border-bottom: 1px solid #e5e7eb; }
    th { background: #f9fafb; font-weight: 600; }
    .recommendations { margin: 24px 0; }
    .recommendations h2 { font-size: 16px; margin-bottom: 8px; }
    .recommendations li { margin: 6px 0; font-size: 13px; }
    .footer { margin-top: 40px; text-align: center; font-size: 11px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 16px; }
    @media print {
      body { padding: 20px; }
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>LATAM Legal Compliance Report</h1>
    <p>${scan.url} — ${new Date(scan.scannedAt).toLocaleDateString('es-CO', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
  </div>

  <div class="score-box">
    <div class="score-number" style="color:${scoreColor}">${scan.score}%</div>
    <div class="score-label">Compliance Score</div>
  </div>

  <div class="summary">
    <span style="color:#22c55e">${scan.summary.pass} passed</span>
    <span style="color:#eab308">${scan.summary.warn} warnings</span>
    <span style="color:#ef4444">${scan.summary.fail} failed</span>
  </div>

  <table>
    <thead>
      <tr><th>Check</th><th>Status</th><th>Details</th><th>Recommendation</th></tr>
    </thead>
    <tbody>
      ${checksHtml}
    </tbody>
  </table>

  ${recommendations ? `
  <div class="recommendations">
    <h2>Priority Recommendations</h2>
    <ul>${recommendations}</ul>
  </div>` : ''}

  <div class="footer">
    <p>Generated by TDE — Transformación Digital Empresarial</p>
    <p>This report is an automated assessment and does not constitute legal advice.</p>
  </div>

  <script class="no-print">window.onload = () => window.print();</script>
</body>
</html>`;
}
